// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRHMoWwcnwNnfoUqi3h4AYegZzFNCqWJg',
    appId: '1:799626897965:web:55d6e4305ba0eda33526a4',
    messagingSenderId: '799626897965',
    projectId: 'eventradar-3a7c6',
    authDomain: 'eventradar-3a7c6.firebaseapp.com',
    storageBucket: 'eventradar-3a7c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaQ8EdmsDYAZbJK_3tC7zpCPWo5dEoUqE',
    appId: '1:799626897965:android:7e4c0fbba72623db3526a4',
    messagingSenderId: '799626897965',
    projectId: 'eventradar-3a7c6',
    storageBucket: 'eventradar-3a7c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_h2F-i2tupn7c7s8lMv2ghQTkfoj4qU',
    appId: '1:799626897965:ios:1610c4c81a3dcca43526a4',
    messagingSenderId: '799626897965',
    projectId: 'eventradar-3a7c6',
    storageBucket: 'eventradar-3a7c6.firebasestorage.app',
    iosBundleId: 'cc.eventradar.eventRadar',
  );
}
